### PR TITLE
Python3 copy

### LINKED ISSUE #152: Python 3.3+ support
pygments.rb is currently using a development version of pygments 2.0.
Python3.3+ is already supported by the release version of pygments 2.0, which was released on Nov 9, 2014. Please pull latest released verison.

Current release from `vendor/pygments-main/CHANGES`

```
Version 2.0
-----------
(under development)

- Dropped Python 2.4 and 2.5 compatibility.  This is in favor of single-source
  compatibility between Python 2.6, 2.7 and 3.3+.
```

Current latest release version

```
Version 2.0.2
-------------
(released Jan 20, 2015)
```

.

### PR DESCRIPTION
**Pull request by ivanistheone**
This is a continuation of the effort started in https://github.com/tmm1/pygments.rb/pull/192/files 
 - resolves #152
 - All tests pass with py3.x on all platforms
 - includes also code from https://github.com/tmm1/pygments.rb/pull/123 since it helped workaround some macOS CI tests failures 
 - suggest release as v1.3.0 even though no code changes, since py2 --> py3 switch is significant

### CODE REVIEW

**Comment by ivanistheone** [comment]
Okay PR is ready. Python3 support!

Credit goes to @terceiro for getting this started and @slonopotamus for figuring our the fix for the windows issue https://github.com/tmm1/pygments.rb/issues/152#issuecomment-680304941

@tmm1 Please take a look and push our a new gem if you think this makes sense (Python 3 much more widely supported now, and in fact default version on most OSs).

**Comment by slonopotamus** [comment]
It not only fails on MacOS, see [this](https://github.com/slonopotamus/pygments.rb/runs/1030293284?check_suite_focus=true).
Looks like 8s is not enough to initialize pygments Python process. Either this needs to be fixed (why it needs so much time?) or time limit needs to be increased.

**Comment by slonopotamus** [comment]
Increasing default timeout to 16 seconds makes it pass, but it feels like a hack. I vote for timeout removal (at least by default). Something like "timeout < 0 means no timeout and default is -1".

**Comment by terceiro** [comment]
@ivanistheone thanks for pushing this forward. I closed my PR in favor or yours.

**Comment by slonopotamus** [comment]
I could also suggest a half-good solution: only apply timeout when highlighting files, not when doing internal interaction (like getting list of lexers) with python process.

**Comment by ivanistheone** [comment]
@slonopotamus Thx for figuring this out.  I found this other PR https://github.com/tmm1/pygments.rb/pull/123 that adds configurable `:timeout` option.

I copied over this `:timeout` option to current PR and set :timeout = for the `lexers!`/`get_all_lexers` call (I first tried with 16 but it was still timing out sporadically). I also added a 1 sec sleep on startup to avoid sending commands to Python "too fast" before it can read them.

Green green green!

**Comment by slonopotamus** [comment]
[This build](https://github.com/tmm1/pygments.rb/runs/1031814817#step:5:27) has 8s between `ruby cache-lexers.rb` and `undefined method `inject' for nil:NilClass (NoMethodError)` error even though you've bumped timeout to 40s.

**Comment by slonopotamus** [comment]
"mega tolerant" also failed after 8s. I think `:timeout` param is not working as you expect it to.

You can enable timestamps in GitHub Actions:

image

**Comment by slonopotamus** [comment]
@gfx ping. Maybe you could review/merge/release this?

**Comment by slonopotamus** [comment]
@ivanistheone you may want to add "resolves #152" text to PR drscription so that #152 will close automatically when this is merged.

**Comment by slonopotamus** [comment]
@tmm1 @gfx ping?

**Comment by gfx** [comment]
Looking 👀

**Comment by tnm** [comment]
Great PR. I'll check it, and merge after review.

Generally: goal is for a few proper semantic releases over the next months to help you all out. Would like to see this lib continue to work for those who need it.

**Pull request closed without merging**
