### PR TITLE
Bump yajl-ruby dependency from 1.1.0 -> 1.2.0

### PR DESCRIPTION
**Pull request by lencioni**
yajl-ruby 1.2.0 was recently released and contains a number of changes:

  https://github.com/brianmario/yajl-ruby/compare/eef5c48be81b6404af66da3f185ec9301e5214d8...fb61daad73340968badf6f84e41ec6931db2e87e

### CODE REVIEW

**Comment by benbalter** [comment]
@tmm1 if you're able to bump yajl-ruby to 1.2.0, I believe this will fix an issue whereby the default Jekyll configuration doesn't work on windows, uncovered while adding Windows testing over in https://github.com/github/pages-gem/pull/112. Monkey patching the Gemfile to require 1.2.0 seems to work, fine, at least in the context of Jekyll, but I didn't test beyond that.

CCing for context, as it took a bit of digging to land here:

* https://github.com/jekyll/jekyll-help/issues/50
* https://github.com/jekyll/jekyll/issues/903
* https://github.com/brianmario/yajl-ruby/issues/116

**Comment by benbalter** [comment]
:sparkles: Thanks @tmm1!

@parkr Pygments `master` should now work on Windows out of the box.

**Comment by parkr** [comment]
> @parkr Pygments master should now work on Windows out of the box.

Thanks, @benbalter! :tada: /cc @XhmikosR

**Comment by XhmikosR** [comment]
Awesome, thanks! Now, we only need a new gem published.

**Comment by adrianmacneil** [comment]
Any chance you can publish a new gem?

**Comment by parkr** [comment]
Bringing in the gem owners: /cc @tmm1 @tnm @vmg Thanks guys!

**Comment by XhmikosR** [comment]
*Bump*

**Comment by tmm1** [comment]
Published 0.6.1 to rubygems

**Comment by parkr** [comment]
Thank you! :tada: :confetti_ball: :pray: :heart:

**Comment by XhmikosR** [comment]
Thanks a million times! This indeed fixes the Windows issue with yajl-ruby and Ruby >= 2.x.

Now, we need a new pages-gem because it has 0.6.0 hardcoded...

**Pull request merged**
