### PR TITLE
resolves #176 exclude find_error.py symlink from gem

### LINKED ISSUE #176: Broken symlink in gem (find_error.py)
For some reason, when the gem is packaged and subsequently installed, the symlink from find_error.py to debug_lexer.py in vendor/pygments-main/scripts. Perhaps we can either delete this symlink or reify it during packaging.

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
I'm not sure if this is how we want to solve it, but it it at least offers a proposal to get us thinking.

**Comment by gfx** [comment]
Can you exclude exactly symlinks? Because pygments is not exactly part of this gem, another symlink may be included in future.

**Comment by mojavelinux** [comment]
There you go.

**Comment by gfx** [comment]
Thanks!

**Comment by gfx** [comment]
Released 1.1.2 with this PR. Check it out!

**Comment by mojavelinux** [comment]
Thanks!

**Pull request merged**
